export const skills: Skill[] = [
  { skillName: 'JavaScript', skillBgColor: '#efd81d' },
  { skillName: 'TypeScript', skillBgColor: '#234a84' },
  { skillName: 'Python', skillBgColor: '#3776ab' },
  { skillName: 'SQL', skillBgColor: '#336791' },
  { skillName: 'React', skillBgColor: '#61dafb' },
  { skillName: 'Next.js', skillBgColor: '#000000' },
  { skillName: 'NestJS', skillBgColor: '#e0234e' },
  { skillName: 'Node.js', skillBgColor: '#339933' },
  { skillName: 'PostgreSQL', skillBgColor: '#336791' },
  { skillName: 'MongoDB', skillBgColor: '#47a248' },
  { skillName: 'Git', skillBgColor: '#e84d31' },
  { skillName: 'AWS', skillBgColor: '#ff9900' },
  { skillName: 'Docker', skillBgColor: '#2496ed' },
  { skillName: 'Vercel', skillBgColor: '#000000' },
  { skillName: 'Ant Design', skillBgColor: '#0170fe' },
  { skillName: 'Tailwind CSS', skillBgColor: '#06b6d4' },
  { skillName: 'Sentry', skillBgColor: '#362d59' },
  { skillName: 'Redux', skillBgColor: '#764abc' },
];
