export const allProjectsThumbnail: ProjectThumbnail[] = [
  {image: '/Sorting-visualizer-thumbnail.png', title: 'Sorting Visualizer', briefDescription: 'A project that helps visualize famous sorting algorithms.'},
  {image: '/3d-clothes-thumbnail.png', title: 'Project 2', briefDescription: 'This is the first project'},
  {image: '/image.png', title: 'Project 3', briefDescription: 'This is the first project'},
  {image: '/image.png', title: 'Project 4', briefDescription: 'This is the first project'},
  {image: '/image.png', title: 'Project 5', briefDescription: 'This is the first project'},
  {image: '/image.png', title: 'Project 6', briefDescription: 'This is the first project'},
  {image: '/image.png', title: 'Project 7', briefDescription: 'This is the first project'},
];

//! The number of these two should be equal!!!!

// ? One is basically the detailed and one is thumbnail both denotes the projects so same number.

export const allProjects: Project[] = [
  {title: 'Sorting Visualizer', detailedDescription: 'A project that helps visualize famous sorting algorithms. Includes algorithms like Bubble Sort, Insertion Sort, Merge Sort, and many others. The idea used is to store the comparisons that will be made and later use audio and visual effects to make it easier for the viewer to understand the working of the algorithm.', stack: [
    {skillName: 'TypeScript', skillBgColor: '#234a84'},
    {skillName: 'ReactJS', skillBgColor: '#5ed3f3'},
    {skillName: 'Next.JS', skillBgColor: '#080808'},
    {skillName: 'TailwindCSS', skillBgColor: '#36b7f0'},
    {skillName: 'Git', skillBgColor: '#e84d31'},
    {skillName: 'Vercel', skillBgColor: '#000000'},
    {skillName: 'JavaScript', skillBgColor: '#efd81d'},
    {skillName: 'Zustand', skillBgColor: '#462e34'},
    // {skillName: 'TypeScript', skillBgColor: '#234a84'},
    // {skillName: 'TypeScript', skillBgColor: '#234a84'},
    // {skillName: 'TypeScript', skillBgColor: '#234a84'},
  ], deploymentLink: 'https://sorting-visualizer-liard.vercel.app/', screenshots: ['/Sorting-visualizer-ss-1.png','/Sorting-visualizer-ss-2.png','/Sorting-visualizer-ss-3.png','/Sorting-visualizer-ss-4.png','/Sorting-visualizer-ss-5.png'], dateAdded: new Date().toLocaleString()},
  {title: 'Project 2', detailedDescription: 'lorem ipsum dolor sit amet, consectetur adip eu fugiat nulla pariatur et accusam et', stack: [
    {skillName: 'JavaScript', skillBgColor: '#234a84'},
    {skillName: 'ReactJS', skillBgColor: '#5ed3f3'},
    {skillName: 'ThreeJS', skillBgColor: '#080808'},
    {skillName: 'TailwindCSS', skillBgColor: '#36b7f0'},
    {skillName: 'Git', skillBgColor: '#e84d31'},
    {skillName: 'Vercel', skillBgColor: '#000000'},
    {skillName: 'Vite', skillBgColor: '#efd81d'},,
    // {skillName: 'TypeScript', skillBgColor: '#234a84'},
    // {skillName: 'TypeScript', skillBgColor: '#234a84'},
    // {skillName: 'TypeScript', skillBgColor: '#234a84'},
  ], deploymentLink: 'https://3-d-clothes-visualizer.vercel.app/', screenshots: ['/3d-clothes-ss1.png','/3d-clothes-ss2.png','/3d-clothes-ss3.png', '/3d-clothes-ss4.png'], dateAdded: new Date().toLocaleString()},
  {title: 'Project 3', detailedDescription: 'lorem ipsum dolor sit amet, consectetur adip eu fugiat nulla pariatur et accusam et', stack: [
    {skillName: 'TypeScript', skillBgColor: '#234a84'},
    {skillName: 'ReactJS', skillBgColor: '#5ed3f3'},
    {skillName: 'Next.JS', skillBgColor: '#080808'},
    {skillName: 'TailwindCSS', skillBgColor: '#36b7f0'},
    {skillName: 'Git', skillBgColor: '#e84d31'},
    {skillName: 'Vercel', skillBgColor: '#000000'},
    {skillName: 'JavaScript', skillBgColor: '#efd81d'},
    {skillName: 'Zustand', skillBgColor: '#462e34'},
    // {skillName: 'TypeScript', skillBgColor: '#234a84'},
    // {skillName: 'TypeScript', skillBgColor: '#234a84'},
    // {skillName: 'TypeScript', skillBgColor: '#234a84'},
  ], deploymentLink: 'www.google.com', screenshots: ['/image.png','/image.png','/image.png'], dateAdded: new Date().toLocaleString()},
  {title: 'Project 4', detailedDescription: 'lorem ipsum dolor sit amet, consectetur adip eu fugiat nulla pariatur et accusam et', stack: [
    {skillName: 'TypeScript', skillBgColor: '#234a84'},
    {skillName: 'ReactJS', skillBgColor: '#5ed3f3'},
    {skillName: 'Next.JS', skillBgColor: '#080808'},
    {skillName: 'TailwindCSS', skillBgColor: '#36b7f0'},
    {skillName: 'Git', skillBgColor: '#e84d31'},
    {skillName: 'Vercel', skillBgColor: '#000000'},
    {skillName: 'JavaScript', skillBgColor: '#efd81d'},
    {skillName: 'Zustand', skillBgColor: '#462e34'},
    // {skillName: 'TypeScript', skillBgColor: '#234a84'},
    // {skillName: 'TypeScript', skillBgColor: '#234a84'},
    // {skillName: 'TypeScript', skillBgColor: '#234a84'},
  ], deploymentLink: 'www.google.com', screenshots: ['/image.png','/image.png','/image.png'], dateAdded: new Date().toLocaleString()},
  {title: 'Project 5', detailedDescription: 'lorem ipsum dolor sit amet, consectetur adip eu fugiat nulla pariatur et accusam et', stack: [
    {skillName: 'TypeScript', skillBgColor: '#234a84'},
    {skillName: 'ReactJS', skillBgColor: '#5ed3f3'},
    {skillName: 'Next.JS', skillBgColor: '#080808'},
    {skillName: 'TailwindCSS', skillBgColor: '#36b7f0'},
    {skillName: 'Git', skillBgColor: '#e84d31'},
    {skillName: 'Vercel', skillBgColor: '#000000'},
    {skillName: 'JavaScript', skillBgColor: '#efd81d'},
    {skillName: 'Zustand', skillBgColor: '#462e34'},
    // {skillName: 'TypeScript', skillBgColor: '#234a84'},
    // {skillName: 'TypeScript', skillBgColor: '#234a84'},
    // {skillName: 'TypeScript', skillBgColor: '#234a84'},
  ], deploymentLink: 'www.google.com', screenshots: ['/image.png','/image.png','/image.png'], dateAdded: new Date().toLocaleString()},
  {title: 'Project 6', detailedDescription: 'lorem ipsum dolor sit amet, consectetur adip eu fugiat nulla pariatur et accusam et', stack: [
    {skillName: 'TypeScript', skillBgColor: '#234a84'},
    {skillName: 'ReactJS', skillBgColor: '#5ed3f3'},
    {skillName: 'Next.JS', skillBgColor: '#080808'},
    {skillName: 'TailwindCSS', skillBgColor: '#36b7f0'},
    {skillName: 'Git', skillBgColor: '#e84d31'},
    {skillName: 'Vercel', skillBgColor: '#000000'},
    {skillName: 'JavaScript', skillBgColor: '#efd81d'},
    {skillName: 'Zustand', skillBgColor: '#462e34'},
    // {skillName: 'TypeScript', skillBgColor: '#234a84'},
    // {skillName: 'TypeScript', skillBgColor: '#234a84'},
    // {skillName: 'TypeScript', skillBgColor: '#234a84'},
  ], deploymentLink: 'www.google.com', screenshots: ['/image.png','/image.png','/image.png'], dateAdded: new Date().toLocaleString()},
  {title: 'Project 7', detailedDescription: 'lorem ipsum dolor sit amet, consectetur adip eu fugiat nulla pariatur et accusam et', stack: [
    {skillName: 'TypeScript', skillBgColor: '#234a84'},
    {skillName: 'ReactJS', skillBgColor: '#5ed3f3'},
    {skillName: 'Next.JS', skillBgColor: '#080808'},
    {skillName: 'TailwindCSS', skillBgColor: '#36b7f0'},
    {skillName: 'Git', skillBgColor: '#e84d31'},
    {skillName: 'Vercel', skillBgColor: '#000000'},
    {skillName: 'JavaScript', skillBgColor: '#efd81d'},
    {skillName: 'Zustand', skillBgColor: '#462e34'},
    // {skillName: 'TypeScript', skillBgColor: '#234a84'},
    // {skillName: 'TypeScript', skillBgColor: '#234a84'},
    // {skillName: 'TypeScript', skillBgColor: '#234a84'},
  ], deploymentLink: 'www.google.com', screenshots: ['/image.png','/image.png','/image.png'], dateAdded: new Date().toLocaleString()},
];